# 是一个 section，可以有多个 section，描述当前项目
[package]
# 项目的名称
name = "hello_world2"
# 项目的版本
version = "0.1.0"
# 使用的 rust 版本
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# 是一个 section，描述项目依赖，依赖也可以称为 crate
[dependencies]
